2023-05-15 22:52:59.720774: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-15 22:53:00.188235: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-05-15 22:53:00.188295: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-05-15 22:53:00.188305: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Simulacao da estrat√©gia:  FedPredict 1
recebeu:  0 Tiny-ImageNet 4 2 0.1 True
create model
Error on line 165 AttributeError 'FedPredictClientTorch' object has no attribute 'input_shape'
Traceback (most recent call last):
  File "/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/simulation.py", line 672, in <module>
    main()
  File "/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/simulation.py", line 667, in main
    simulation.start_simulation()
  File "/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/simulation.py", line 624, in start_simulation
    strategy      = self.create_strategy(),
  File "/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/simulation.py", line 439, in create_strategy
    model=copy.deepcopy(self.create_client(0).create_model()),
  File "/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/simulation.py", line 155, in create_client
    return FedPredictClientTorch(cid=cid,
  File "/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/client/client_torch/fedpredict_client_torch.py", line 44, in __init__
    super().__init__(cid=cid,
  File "/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/client/client_torch/fedavg_client_torch.py", line 31, in __init__
    super().__init__(cid=cid,
  File "/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/client/client_torch/client_base_torch.py", line 126, in __init__
    self.model                                           = self.create_model().to(self.device)
AttributeError: 'NoneType' object has no attribute 'to'
4   ['FedPredict']
antes:  None FedPredict-None-1.0
{'FedPredict': '/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/logs/torch/FedPredict-None-1.0/new_clients_False_train_False/4/CNN/Tiny-ImageNet/classes_per_client_2/alpha_0.1/2_rounds/1_local_epochs/_comment/4_layer_selection_evaluate/'}
Traceback (most recent call last):
  File "analysis/non_iid.py", line 382, in <module>
    c.start('Exp. ' + str(int(opt.experiment)-1) + " (" + dataset + ");" + "Alpha="+str(opt.alpha)+"; Layer order="+comment+"; Shared layers="+str(opt.layer_selection_evaluate))
  File "analysis/non_iid.py", line 105, in start
    df = pd.read_csv(models_directories[strategy_name]+file_name)
  File "/home/claudio/Documentos/virtual_environments/FedLTA/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/claudio/Documentos/virtual_environments/FedLTA/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/claudio/Documentos/virtual_environments/FedLTA/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/claudio/Documentos/virtual_environments/FedLTA/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/claudio/Documentos/virtual_environments/FedLTA/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/claudio/Documentos/virtual_environments/FedLTA/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/claudio/Documentos/virtual_environments/FedLTA/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/claudio/Documentos/pycharm_projects/FL-H.IAAC/logs/torch/FedPredict-None-1.0/new_clients_False_train_False/4/CNN/Tiny-ImageNet/classes_per_client_2/alpha_0.1/2_rounds/1_local_epochs/_comment/4_layer_selection_evaluate/evaluate_client.csv'
Starting FedPredict fraction_fit-1 simulation for Tiny-ImageNet clients with CNN model ... /home/claudio/Documentos/pycharm_projects/FL-H.IAAC
=====================================
Executando... 
 python /home/claudio/Documentos/pycharm_projects/FL-H.IAAC/simulation.py --dataset='Tiny-ImageNet' --model='CNN' --strategy='FedPredict' --epochs=1 --round=2 --client=4 --type='torch' --non-iid=True --aggregation_method='None' --fraction_fit=1 --poc=0 --new_clients=False --new_clients_train=False --decay=0 --comment= --class_per_client=2 --alpha=0.1 --layer_selection_evaluate=4 
=====================================
=====================================
Executando analytics... 
 python analysis/non_iid.py --dataset='Tiny-ImageNet' --model='CNN' --round=2 --client=4 --aggregation_method='None' --poc=0 --new_clients=False --new_clients_train=False --non-iid=True --comment='' --epochs=1 --decay=0 --fraction_fit=1 --class_per_client=2 --alpha=0.1 --layer_selection_evaluate=4 --experiment=2  --strategy='FedPredict' 
=====================================
